### ISSUE TITLE
Update start menu when taskbar is arranged vertically

### ISSUE THREAD

**Issue by jonathan-rogers-dev** [bonzibudd/Fluent-Metro#120]
### Describe the bug and specify what is affected
When the taskbar is arranged vertically, the start menu is aligned to the right (when the taskbar is on the right). There is a similar effect when the taskbar is on the left.

### What you expected
The start menu should not cover the taskbar.

### Screenshots
![image](https://user-images.githubusercontent.com/39242954/115789435-26b75080-a393-11eb-853c-a8e05b6a819e.png)

### Version:
 - OS: [e.g. Windows 10]
 - Fluent-Metro: [e.g. v1.4]

**Comment by bonzibudd** [comment]
This can be toggled in Open-Shell, search for "Show next to taskbar" and it should allow it to float from the edge.
