### ISSUE TITLE
Can we have an option that allow us to resize the menu ??

### ISSUE THREAD

**Issue by ImZary** [bonzibudd/Fluent-Metro#130]
Hello !, i today came here to ask if it's possible in some way that we can at least be able to resize the menu, since there is a Huge gap between the main menu, & the edge of the screen as showed in the screenshots you took.

this could help us make the menu smaller, & make it look more cleaner :D

& that's it !, i just would like if it's possible to allow us to resize it :D

EDIT : Nevermind, there IS an option, it's just not that clear Go to Menu Border Style, & choose Classic

**Comment by ImZary** [comment]
Nevermind, it's fixed

**Comment by bonzibudd** [comment]
I will probably end up making some changes, because several people have brought this up. I might do one of two things:
 - Place the toggle higher up in the options
 - Make the default style the Classic border

**Comment by sinankizar** [comment]
I think adding an option to resize for border and/or border space. I personally prefer floating menu a little  closer to screen border and taskbar.

**Comment by bonzibudd** [comment]
@sinankizar you can do that with the latest Open-Shell [nightly build](https://ci.appveyor.com/project/passionate-coder/open-shell-menu/branch/master/artifacts). When it is installed, search for "offset" in the Menu settings and you can manually change the positioning.

**Comment by sinankizar** [comment]
> @sinankizar you can do that with the latest Open-Shell [nightly build](https://ci.appveyor.com/project/passionate-coder/open-shell-menu/branch/master/artifacts). When it is installed, search for "offset" in the Menu settings and you can manually change the positioning.

Thank you so much for pointing this one. Now my desktop looks awesome 👏🏻

**Comment by bonzibudd** [comment]
I'm closing this for now, I've made the "Classic" border the default and put it slightly higher in the options list.
