### ISSUE TITLE
Change the menu background color

### ISSUE THREAD

**Issue by sinankizar** [bonzibudd/Fluent-Metro#131]
Hello,
First off I want to thank you for your efforts. This skin is awesome. It brings fresh look to my elderly metro skin :)

I want to be able to change the color because my taskbar is transparent and never getting the right colour to match the menu. I think it is not totally black, when I set to opaque, the menu looks a little different from pitch black.

If there is a way I will happily test it, if there is not at hand can you please add this feature?

Thanks a billion....

![Untitled](https://user-images.githubusercontent.com/28201097/116821638-54ff1200-ab83-11eb-9b09-efb1ffce412a.png)

**Comment by bonzibudd** [comment]
Yes, I think I should be able to add that as an option. It currently uses the same color as the Windows 10 Start Menu by default, which isn't completely black. It may not be in the nearest release, but I will try to have it ready by the next final version.

**Comment by sinankizar** [comment]
You are the man. Thank you again. I am trying all the pre-betas right now for newest features🤣

**Comment by bonzibudd** [comment]
I added a new version which has this option: [prebeta4](https://github.com/bonzibudd/Fluent-Metro/blob/master/Development/Fluent-Metro_1.5prebeta4.skin7)

It may not be completely finished, but it should be mostly functional.

**Comment by sinankizar** [comment]
> I added a new version which has this option: [prebeta4](https://github.com/bonzibudd/Fluent-Metro/blob/master/Development/Fluent-Metro_1.5prebeta4.skin7)
> 
> It may not be completely finished, but it should be mostly functional.

Thank you! Now this is more like it :) Can change color and I am very happy with the result.

**Comment by bonzibudd** [comment]
Addressed #131 in release 1.5.
