### ISSUE TITLE
Add custom color for sub menu

### ISSUE THREAD

**Issue by komawoyo** [bonzibudd/Fluent-Metro#170]
### Describe the proposed feature
Add ability to add custom menu color similar to main menu.
 
### Explain how the feature may be useful
In the image below the colors are not linked so it does not look as good. 

### Screenshots
![image](https://user-images.githubusercontent.com/18315233/152910383-a0325567-fc59-400d-a94a-1f4098ed9de3.png)

**Comment by bonzibudd** [comment]
Thank you for the feedback! I will definitely consider this as an option for future releases.

**Comment by bonzibudd** [comment]
Addressed #170 in release 1.5.3.
