### ISSUE TITLE
Windows 10 power button does not function 

### ISSUE THREAD

**Issue by asianmusicguy** [bonzibudd/Fluent-Metro#46]
Windows turn off button when selected  via skin off button does not function normally and does not turn off PC  rather simply behaves as a right click

**Comment by bonzibudd** [comment]
Sorry, I need some clarification. Are you talking about the standard shutdown button:
![image](https://user-images.githubusercontent.com/61938331/99013817-58dca080-251f-11eb-9889-d6623ccaad0b.png)
Or the Windows 10 style button:
![image](https://user-images.githubusercontent.com/61938331/99013887-80336d80-251f-11eb-945c-356428ac39c9.png)

If you are using the standard style, you can just left-click the arrow to bring up the submenu. For the Windows 10 style, the entire section should be left-clickable to open the context menu. You also need to make sure that the "Shutdown command" option in the Main menu tab is set to "Shutdown dialog" for the context menu items to display correctly:
![image](https://user-images.githubusercontent.com/61938331/99014436-a3aae800-2520-11eb-90f8-9d3d59e5df0b.png)

**Comment by asianmusicguy** [comment]
ah ok i see my mistake
