### ISSUE TITLE
[Feature Request] Bigger user profile picture

### ISSUE THREAD

**Issue by Darthagnon** [bonzibudd/Fluent-Metro#47]
Would it please be possible to implement a slightly bigger user profile picture option for the skin? Especially when set to "outside", the profile picture looks significantly smaller than e.g. the Aero square profile pic, and smaller than the "Documents", "Music", etc. icons that appear.

I measured the Aero profile pic, and on my PC it's a 56x56 px square (diagonal is hence ~79px); to feel the same size as the aero profile pic (and hence, the same as the other popup icons), I feel the circular profile pic  (same system: 50px diameter circle), to feel "the same size" as the square, should perhaps have an option to set the diameter to 79px (diagonal of the square) (or somewhere between 56px and 79px), as even a 56px circle is going to "feel" smaller (by the corners) than a 56px square

**Comment by bonzibudd** [comment]
This should be possible. I’ll probably end up with around 3 or 4 sizes somewhere in that 48px-79px range.

**Comment by Darthagnon** [comment]
Thank you so much, Bonzibudd!

**Comment by bonzibudd** [comment]
I finally added this: 
![image](https://user-images.githubusercontent.com/61938331/104524901-18f07300-55cd-11eb-9f88-eab4beabe0dc.png)

I am planning to do a new prerelease in the next few days. I have some other changes I need to implement as well.

**Comment by Darthagnon** [comment]
Thank you so much!

**Comment by bonzibudd** [comment]
Addressed #47 in release 1.3.
