### ISSUE TITLE
Big Icon on Compact Menu Size

### ISSUE THREAD

**Issue by kraith** [bonzibudd/Fluent-Metro#86]
Please add Big Icon size on Compact Menu Size, I like compact size because submenu padding is smaller than default one
In screenshot I already edited with recourcehacker to change big icon to 1
![Screenshot (24)](https://user-images.githubusercontent.com/55749240/112995811-cec36a80-9195-11eb-8ed8-daeb6d405954.png)

**Comment by bonzibudd** [comment]
Good idea. The small submenu will probably become a separate option for this exact purpose. That way, you could use the "Standard with smaller right-hand items" option to retain the large icons.

**Comment by bonzibudd** [comment]
![Compact sub-menu](https://user-images.githubusercontent.com/61938331/113065760-5c4b8e00-9187-11eb-88f9-4ba29727816f.png)
Here's the new option. The compact sub-menu can be enabled on all main menu sizes.

**Comment by bonzibudd** [comment]
Addressed #86 in release 1.4.

**Comment by bonzibudd** [comment]
@kraith Just to confirm, does the latest release solve your problem?

**Comment by kraith** [comment]
Yes, that's what I want.
Thank you.
